# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_database_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritemovies',
            name='poster_path',
            field=models.CharField(default='/eHQyaDZcAm5dZOTEyT2lxZvUh6i.jpg', max_length=200),
            preserve_default=False,
        ),
    ]
